### PR TITLE
Support split editor

### PR DESCRIPTION
**Pull request by CsCherrYY**
Eclipse:
spliteditor

VSCode:
image

### CODE REVIEW

**Comment by p-** [comment]
@CsCherrYY Does this key combination work for you?
We removed it here:
https://github.com/alphabotsec/vscode-eclipse-keybindings/pull/24
since it didn't seem to work...

**Comment by CsCherrYY** [comment]
it works for me.

split

The previous solution is using `ctrl+{` but in my PR it's `ctrl+shift+[`, that's might be the gap (VS Code may recognize `shift+[` instead of `{`)

**Comment by p-** [comment]
>The previous solution is using ctrl+{ but in my PR it's ctrl+shift+[, that's might be the gap (VS Code may recognize shift+[ instead of {)

I see. Is ctrl+shift+[ an alternative keybinding for split editor in Eclipse? (If not: what is the benefit of providing a keybinding, that is not the same as in Eclipse as part of these eclipse-keybindings?)
I typically just use `ctrl+2`/`cmd+2` these days.

**Comment by CsCherrYY** [comment]
in eclipse default keybindings it's `{`, but actually we should type `shift+[` in the keyboard to get `{`, that's why I regard they are the same.

**Comment by p-** [comment]
>in eclipse default keybindings it's {, but actually we should type shift+[ in the keyboard to get {, that's why I regard they are the same.

I see, but that's only true for english keyboard layouts. It's not true for many other keyboard layouts. So I'll think we'd better wait until VS Code supports the `ctrl+{`-keybinding directly.

**Comment by CsCherrYY** [comment]
> > in eclipse default keybindings it's {, but actually we should type shift+[ in the keyboard to get {, that's why I regard they are the same.
> 
> I see, but that's only true for english keyboard layouts. It's not true for many other keyboard layouts. So I'll think we'd better wait until VS Code supports the `ctrl+{`-keybinding directly.

Agree!👍I can rebase this PR then

**Comment by CsCherrYY** [comment]
@p- regarding the other keyboard layouts (non-English ones), could you share some contents about these layouts? e.g., 

- how to trigger `{` in your keyboard layout?
- how to trigger "split editor" in eclipse in your keyboard layout?

**Comment by p-** [comment]
Hi @CsCherrYY 
We can merge this change again. There seems to be no good solution for the other keyboard layouts. It's a little bit an unfortunate situation. Pressing `ctrl/cmd+2` is probably the best workaround for people that use German/French/Swiss-German/etc keyboard layouts.

**Pull request merged**
