### PR TITLE
Add "Go to Bracket" shortcut

### PR DESCRIPTION
**Pull request by metric152**

### CODE REVIEW

**Comment by metric152** [comment]
Hey there. Wanted to draw attention to the PR. It's been a little bit.

**Comment by p-** [comment]
Hey @metric152 
First of thanks for your contribution!

But I don't know if it's a good idea to add Ctrl+Shift+P to the keybindings since I know that some people use that binding to open the Command Palette (like Ctrl+3).
And adding that keybinding might break their expected behavior.

**Comment by metric152** [comment]
I was hoping to mirror the eclipse command. I understand if that key binding is used for something more popular. Feel free to close the PR

**Comment by p-** [comment]
Closing this pull-request, I might reconsider it another time.

**Pull request closed without merging**
